### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by Aradig26** [DavidBerdik/YouTube-Stream-Repeater#2]
How to install this? I have installed https://github.com/wes1993/YouTubeForAlexa but dont know how to continue

**Comment by DavidBerdik** [comment]
If you use Home Assistant, then the recommended approach for using this is to use wes1993's addon. Instructions for using that are available in his README [here](https://github.com/wes1993/YouTubeForAlexa#extra-step-1-really-reccommended).

If you don't use Home Assistant, then you need to instead use this repo to build a Docker image and deploy a container on a server that you host yourself. Alexa requires that the URLs passed to it for audio playback use HTTPS, and this container does not, so you will need to configure a reverse proxy on top of it. I use [this prebuilt Docker image](https://hub.docker.com/r/linuxserver/swag) to configure my reverse proxy.
