### ISSUE TITLE
Container logs pending at `"GET /meta/XXXX HTTP/1.1" 200 OK`

### ISSUE THREAD

**Issue by hoangmnsd** [DavidBerdik/YouTube-Stream-Repeater#5]
Hello David,

I use this docker image for a while and it works great. Recently I see that Alexa not playing any more, Alexa says: "The video/playlist hasn't work, should I try the next one?"

I check the log in docker container, it is pending at `GET /meta/XXXX` and never send stream video to Alexa anymore.

```
INFO:     Uvicorn running on http://0.0.0.0:4000 (Press CTRL+C to quit)
INFO:     Started parent process [1]
INFO:     Started server process [12]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Started server process [10]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Started server process [8]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Started server process [14]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Started server process [9]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Started server process [13]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Started server process [11]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Started server process [15]
INFO:     Waiting for application startup.
INFO:     Application startup complete.



INFO:     172.18.0.2:52560 - "GET /meta/DAxxxxxc HTTP/1.1" 200 OK
INFO:     172.18.0.2:42592 - "GET /meta/l9xxxxxx4 HTTP/1.1" 200 OK
```

Not sure if you're facing this issue or not?
How can I debug this error?

Thanks in advanced

**Comment by DavidBerdik** [comment]
Hello!

Based on what you have said, I am guessing that you probably have not rebuilt your Docker image in a while. Please do so using the latest changes in this repository.

If you are still having issues after doing that, please let me know.

**Comment by hoangmnsd** [comment]
Sorry for late reply, I already rebuilt the image with `--no-cache` flag. And this issue still persists...

**Comment by DavidBerdik** [comment]
Could you give me a test video to try? I have not been able to reproduce this.

**Comment by hoangmnsd** [comment]
Sorry it is hard to make a video. But I can share the log in my Lambda function and containers logs:
Lambda function trigger your service:
![image](https://github.com/DavidBerdik/YouTube-Stream-Repeater/assets/12986552/b301aa11-473a-43d6-9bfc-2cd88268597c)

Your service container logs:
![image](https://github.com/DavidBerdik/YouTube-Stream-Repeater/assets/12986552/779efc81-a021-4b39-9c4c-4291da000f61)

**Comment by DavidBerdik** [comment]
Unfortunately, I don't see anything in here that looks abnormal.

The only thing that stands out to me is the entry for the video with ID `KzV_UCQFY6w`, but since it is private, this is expected.

**Comment by hoangmnsd** [comment]
Hi @DavidBerdik , today I had time to figure it out. The issue lies in the Lambda function:
https://github.com/DavidBerdik/YouTubeForAlexa-Lambda/blob/e42f697be5818977c4912f04c4dcec2508342578/lambda_function.py#L1204

`if playlist_channel_video != strings['video'] and (datetime.now() - startTime).total_seconds() > 8:`

I recommend increasing the duration to longer than 8 seconds. Otherwise, it may occasionally result in this error.
